#!/usr/bin/env python3
"""Generate a SQL script to insert dishes into Supabase.

Reads scripts/output/dishes_with_ingredients.json and produces
scripts/output/import_menus.sql — paste it into the Supabase SQL editor.

Usage:
    python3 scripts/generate_sql.py
"""

import json
import os

IN_FILE = "scripts/output/dishes_with_ingredients.json"
OUT_FILE = "scripts/output/import_menus.sql"

MEAL_TYPE_PRIORITY = ["diner", "dejeuner", "petit-dejeuner", "gouter"]


def esc(s: str) -> str:
    """Escape single quotes for SQL string literals."""
    return s.replace("'", "''")


def main():
    dishes = json.load(open(IN_FILE, encoding="utf-8"))
    to_import = [d for d in dishes if not d.get("error") or d.get("ingredients")]
    print(f"Generating SQL for {len(to_import)} dishes...")

    lines = [
        "-- Scout-menu: import default dishes from SGDF camp menus",
        "-- Generated by scripts/generate_sql.py",
        "-- Run in Supabase SQL editor (Dashboard → SQL Editor → New query)",
        "",
        "DO $$",
        "DECLARE",
        "  v_menu_id UUID;",
        "BEGIN",
        "",
    ]

    skipped = 0
    for dish in to_import:
        name = dish["name"]
        ingredients = dish.get("ingredients", [])

        meal_types = dish.get("meal_types", [])
        meal_type = next((t for t in MEAL_TYPE_PRIORITY if t in meal_types), meal_types[0] if meal_types else "diner")

        lines.append(f"  -- {name}")
        lines.append(f"  IF NOT EXISTS (SELECT 1 FROM public.menus WHERE name = '{esc(name)}' AND is_default = true) THEN")
        lines.append(f"    INSERT INTO public.menus (name, meal_type, is_default, user_id)")
        lines.append(f"    VALUES ('{esc(name)}', '{meal_type}', true, NULL)")
        lines.append(f"    RETURNING id INTO v_menu_id;")

        if ingredients:
            for ing in ingredients:
                ing_name = esc(ing["name"])
                qty = ing["quantity"]
                unit = esc(ing["unit"])
                lines.append(f"    INSERT INTO public.menu_ingredients (menu_id, name, quantity, unit)")
                lines.append(f"    VALUES (v_menu_id, '{ing_name}', {qty}, '{unit}');")

        lines.append(f"  END IF;")
        lines.append("")

    lines += [
        "END $$;",
        "",
        "SELECT COUNT(*) AS total_default_menus FROM public.menus WHERE is_default = true;",
    ]

    sql = "\n".join(lines)
    os.makedirs("scripts/output", exist_ok=True)
    with open(OUT_FILE, "w", encoding="utf-8") as f:
        f.write(sql)

    print(f"Done → {OUT_FILE} ({len(sql):,} bytes)")
    print(f"Paste into: https://supabase.com/dashboard/project/yjbrzyjdapvfaknjltxm/sql/new")


if __name__ == "__main__":
    main()
