#!/usr/bin/env python3
"""Generate a SQL script to insert dishes into Supabase.

Reads scripts/output/dishes_with_ingredients.json and produces
scripts/output/import_menus.sql — paste it into the Supabase SQL editor.

If scripts/output/ingredient_agribalyse_map.json exists, each ingredient
INSERT will include agribalyse_food_id and unit_multiplier.

Usage:
    python3 scripts/generate_sql.py
"""

import csv
import json
import os
import re
import unicodedata

IN_FILE = "scripts/output/dishes_with_ingredients.json"
AGRIBALYSE_MAP_FILE = "scripts/output/ingredient_agribalyse_map.json"
RATIO_CSV_FILE = "scripts/data/agribalyse_default_ratios.csv"
OUT_FILE = "scripts/output/import_menus.sql"

MEAL_TYPE_PRIORITY = ["diner", "dejeuner", "petit-dejeuner", "gouter"]


def esc(s: str) -> str:
    return s.replace("'", "''")


def get_fallback_ratio(unit: str) -> float:
    if unit == "g":
        return 1.0
    if unit == "kg":
        return 1000.0
    return 1000.0


def load_ratio_rows(path: str) -> list:
    rows = []
    with open(path, encoding="utf-8") as fh:
        reader = csv.reader(fh, delimiter=";")
        for line in reader:
            if not line:
                continue
            raw = line[0].strip()
            if raw.startswith("#") or raw == "name_pattern":
                continue
            if len(line) < 3:
                continue
            try:
                grams = float(line[2].strip())
            except ValueError:
                continue
            rows.append({
                "name_pattern": line[0].strip(),
                "unit": line[1].strip(),
                "grams_per_unit": grams,
            })
    return rows


_LIGATURES = str.maketrans({"Œ": "oe", "œ": "oe", "Æ": "ae", "æ": "ae"})


def _normalize(s: str) -> str:
    s = s.translate(_LIGATURES)
    return unicodedata.normalize("NFD", s).encode("ascii", "ignore").decode("ascii").lower()


def _ilike_match(pattern: str, text: str) -> bool:
    regex = ".*".join(re.escape(seg) for seg in _normalize(pattern).split("%") if seg)
    return bool(re.fullmatch(f".*{regex}.*", _normalize(text))) if regex else True


def get_unit_multiplier(agribalyse_name, unit: str, ratio_rows: list) -> float:
    if agribalyse_name and unit not in ("g", "kg"):
        for row in ratio_rows:
            if row["unit"] == unit and _ilike_match(row["name_pattern"], agribalyse_name):
                return row["grams_per_unit"]
    return get_fallback_ratio(unit)


def main():
    with open(IN_FILE, encoding="utf-8") as fh:
        dishes = json.load(fh)
    to_import = [d for d in dishes if not d.get("error") or d.get("ingredients")]
    print(f"Generating SQL for {len(to_import)} dishes...")

    agribalyse_map = {}
    if os.path.exists(AGRIBALYSE_MAP_FILE):
        with open(AGRIBALYSE_MAP_FILE, encoding="utf-8") as fh:
            agribalyse_map = json.load(fh)
        print(f"Loaded Agribalyse map: {sum(1 for v in agribalyse_map.values() if v)} matches")

    ratio_rows = []
    if os.path.exists(RATIO_CSV_FILE):
        ratio_rows = load_ratio_rows(RATIO_CSV_FILE)

    lines = [
        "-- Scout-menu: import default dishes from SGDF camp menus",
        "-- Generated by scripts/generate_sql.py",
        "-- Run in Supabase SQL editor (Dashboard → SQL Editor → New query)",
        "",
        "-- Clear existing default dishes (re-imported with Agribalyse linkage below)",
        "-- NOTE: DELETE and DO block are separate statements. If the DO block fails mid-run,",
        "-- re-run the full script to restore the deleted dishes.",
        "DELETE FROM public.menus WHERE is_default = true AND user_id IS NULL;",
        "",
        "DO $$",
        "DECLARE",
        "  v_menu_id UUID;",
        "BEGIN",
        "",
    ]

    for dish in to_import:
        name = dish["name"]
        ingredients = dish.get("ingredients", [])
        meal_types = dish.get("meal_types", [])
        meal_type = next((t for t in MEAL_TYPE_PRIORITY if t in meal_types), meal_types[0] if meal_types else "diner")

        lines.append(f"  -- {name}")
        lines.append(f"  INSERT INTO public.menus (name, meal_type, is_default, user_id)")
        lines.append(f"  VALUES ('{esc(name)}', '{meal_type}', true, NULL)")
        lines.append(f"  RETURNING id INTO v_menu_id;")

        if ingredients:
            for ing in ingredients:
                ing_name = ing["name"]
                qty = ing["quantity"]
                unit = ing["unit"]
                agribalyse_name = agribalyse_map.get(ing_name)
                multiplier = get_unit_multiplier(agribalyse_name, unit, ratio_rows)

                if agribalyse_name:
                    agri_subquery = f"(SELECT id FROM agribalyse_foods WHERE name = '{esc(agribalyse_name)}' LIMIT 1)"
                else:
                    agri_subquery = "NULL"

                lines.append(
                    f"  INSERT INTO public.menu_ingredients "
                    f"(menu_id, name, quantity, unit, agribalyse_food_id, unit_multiplier)"
                )
                lines.append(
                    f"  VALUES (v_menu_id, '{esc(ing_name)}', {qty}, '{esc(unit)}', "
                    f"{agri_subquery}, {multiplier});"
                )

        lines.append("")

    lines += [
        "END $$;",
        "",
        "SELECT COUNT(*) AS total_default_menus FROM public.menus WHERE is_default = true;",
    ]

    sql = "\n".join(lines)
    os.makedirs("scripts/output", exist_ok=True)
    with open(OUT_FILE, "w", encoding="utf-8") as f:
        f.write(sql)

    print(f"Done → {OUT_FILE} ({len(sql):,} bytes)")
    print(f"Paste into: https://supabase.com/dashboard/project/yjbrzyjdapvfaknjltxm/sql/new")


if __name__ == "__main__":
    main()
