#!/usr/bin/env python3
"""Generate import SQL from dishes_final.csv.

Reads scripts/output/dishes_final.csv and produces scripts/output/import_menus.sql.
The CSV is the authoritative source: agribalyse_match and unit_multiplier are taken as-is.

Usage:
    python3 scripts/generate_sql_from_final.py [--user-email EMAIL]
"""

import argparse
import csv
import os
import sys
from collections import OrderedDict

sys.path.insert(0, os.path.dirname(__file__))
from generate_sql import MEAL_TYPE_PRIORITY, cap_first, esc

IN_FILE = "scripts/output/dishes_final.csv"
OUT_FILE = "scripts/output/import_menus.sql"


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--user-email", help="Attach menus to this user account instead of NULL")
    args = parser.parse_args()
    user_email = args.user_email

    rows = []
    with open(IN_FILE, encoding="utf-8-sig") as fh:
        reader = csv.DictReader(fh, delimiter=";")
        for row in reader:
            rows.append(row)

    # Group rows by dish_name, preserving insertion order
    dishes: dict[str, dict] = OrderedDict()
    for row in rows:
        name = row["dish_name"].strip()
        if name not in dishes:
            dishes[name] = {
                "meal_types": [t.strip() for t in row["meal_types"].split(",") if t.strip()],
                "ingredients": [],
            }
        dishes[name]["ingredients"].append(row)

    print(f"Generating SQL for {len(dishes)} dishes ({len(rows)} ingredient rows)...")

    if user_email:
        user_id_expr = f"(SELECT id FROM auth.users WHERE email = '{esc(user_email)}' LIMIT 1)"
        delete_clause = f"user_id = (SELECT id FROM auth.users WHERE email = '{esc(user_email)}' LIMIT 1)"
        delete_comment = f"-- Clear existing default dishes for {user_email} (re-imported below)"
    else:
        user_id_expr = "NULL"
        delete_clause = "user_id IS NULL"
        delete_comment = "-- Clear existing default dishes (re-imported below)"

    lines = [
        "-- Scout-menu: import default dishes from dishes_final.csv",
        "-- Generated by scripts/generate_sql_from_final.py",
        "-- Run in Supabase SQL editor (Dashboard → SQL Editor → New query)",
        "",
        delete_comment,
        "-- NOTE: DELETE and DO block are separate statements. If the DO block fails mid-run,",
        "-- re-run the full script to restore the deleted dishes.",
        f"DELETE FROM public.menus WHERE is_default = true AND {delete_clause};",
        "",
        "DO $$",
        "DECLARE",
        "  v_menu_id UUID;",
        "BEGIN",
        "",
    ]

    for dish_name, dish in dishes.items():
        name = cap_first(dish_name)
        meal_types = dish["meal_types"]
        meal_type = next((t for t in MEAL_TYPE_PRIORITY if t in meal_types), meal_types[0] if meal_types else "diner")

        lines.append(f"  -- {name}")
        lines.append(f"  INSERT INTO public.menus (name, meal_type, is_default, user_id)")
        lines.append(f"  VALUES ('{esc(name)}', '{meal_type}', true, {user_id_expr})")
        lines.append(f"  RETURNING id INTO v_menu_id;")

        for ing in dish["ingredients"]:
            ing_name = cap_first(ing["ingredient_name"].strip())
            qty = ing["quantity"].strip()
            unit = ing["unit"].strip()
            agribalyse_match = ing["agribalyse_match"].strip()
            unit_multiplier = ing["unit_multiplier"].strip()

            if agribalyse_match:
                agri_subquery = f"(SELECT id FROM agribalyse_foods WHERE name = '{esc(agribalyse_match)}' LIMIT 1)"
            else:
                agri_subquery = "NULL"

            lines.append(
                f"  INSERT INTO public.menu_ingredients "
                f"(menu_id, name, quantity, unit, agribalyse_food_id, unit_multiplier)"
            )
            lines.append(
                f"  VALUES (v_menu_id, '{esc(ing_name)}', {qty}, '{esc(unit)}', "
                f"{agri_subquery}, {unit_multiplier});"
            )

        lines.append("")

    count_clause = f"is_default = true AND {delete_clause}"
    lines += [
        "END $$;",
        "",
        f"SELECT COUNT(*) AS total_default_menus FROM public.menus WHERE {count_clause};",
    ]

    sql = "\n".join(lines)
    os.makedirs("scripts/output", exist_ok=True)
    with open(OUT_FILE, "w", encoding="utf-8") as f:
        f.write(sql)

    print(f"Done → {OUT_FILE} ({len(sql):,} bytes)")
    print(f"Paste into: https://supabase.com/dashboard/project/yjbrzyjdapvfaknjltxm/sql/new")


if __name__ == "__main__":
    main()
